---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kbot-telegram
  namespace: demo
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/vladyslavPlaksa/kbot-telegram
